apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-server-deployment
  name: fastapi-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-server-deployment
  template:
    metadata:
      labels:
        app: fastapi-server-deployment
    spec:
      containers:
        - name: fastapi-server
          image: precioux/fastapi-server:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: server-config
