apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - name: fastapi-server
          image: <your-image-name>
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-cache
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: code-volume
              mountPath: /app
      volumes:
        - name: config-volume
          configMap:
            name: fastapi-server-config
        - name: code-volume
          configMap:
            name: fastapi-server-code
