apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-deployment
spec:
  type: LoadBalancer
  selector:
    app: fastapi-server-deployment
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
