apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
spec:
  type: LoadBalancer
  selector:
    app: fastapi-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
