apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server-deployment
  labels:
    app: fastapi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - name: fastapi-server-container
        image: fastapi-server:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: fastapi-server-config
